### ISSUE TITLE
Parquet: List offset error when written in chunks

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#1132]
Writing a parquet file consisting of two arrow `Chunk`s and then two row groups (I believe) leads to invalid list offsets.

The following snippet creates a `DataFrame` with two arrow `Chunk`s and writes that to parquet. The `DataFrame` looks like this:

```
shape: (70, 2)
┌─────┬───────────────┐
│ a   ┆ l             │
│ --- ┆ ---           │
│ i64 ┆ list[i64]     │
╞═════╪═══════════════╡
│ 0   ┆ [0, 1, ... 4] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ [0, 1, ... 5] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ [0, 1, ... 4] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ [0, 1, ... 5] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ... ┆ ...           │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ [0, 1, ... 3] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9   ┆ [0, 1, ... 4] │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 6   ┆ [0, 1, 2]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7   ┆ [0, 1, ... 3] │
└─────┴───────────────┘

```

```python
import polars as pl
import numpy as np

df1 = pl.DataFrame({'a': np.random.randint(0, high=10, size=20), 'l': [[i for i in range(0, 5 + j%2)] for j in range(0, 20)]})
df2 = pl.DataFrame({'a': np.random.randint(0, high=10, size=50), 'l': [[i for i in range(0, 3 + j%3)] for j in range(0, 50)]})
df = df1.vstack(df2)
print(df)

for use_pyarrow in [False, True]:
    f = io.BytesIO()
    df.to_parquet(f)
    f.seek(0)

    assert pl.read_parquet(f, use_pyarrow=use_pyarrow).frame_equal(df)
```

Pyarrow is able to read this.

## Output
Below shows the output of the snippet. I compiled with a `dbg!` statement of the `offsets` at the point of panic.

```
[/home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:48] &offsets = [
    0,
    5,
    11,
    16,
    22,
    27,
    33,
    38,
    44,
    49,
    55,
    60,
    66,
    71,
    77,
    82,
    88,
    93,
    99,
    104,
]
[/home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:63] &offsets = [
    0,
    5,
    11,
    16,
    22,
    27,
    33,
    38,
    44,
    49,
    55,
    60,
    66,
    71,
    77,
    82,
    88,
    93,
    99,
    104,
    110,
]
[/home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:48] &offsets = [
    0,
    3,
    7,
    12,
    15,
    19,
    24,
    27,
    31,
    36,
    39,
    43,
    48,
    51,
    55,
    60,
    63,
    67,
    72,
    75,
    79,
]
[/home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:63] &offsets = [
    0,
    3,
    7,
    12,
    15,
    19,
    24,
    27,
    31,
    36,
    39,
    43,
    48,
    51,
    55,
    60,
    63,
    67,
    72,
    75,
    79,
    31,
]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("offsets must be monotonically increasing")', /home/ritchie46/code/arrow2/src/array/list/mod.rs:92:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/result.rs:1098:23
   4: arrow2::array::list::ListArray<O>::new
             at /home/ritchie46/code/arrow2/src/array/list/mod.rs:92:9
   5: arrow2::io::parquet::read::deserialize::create_list
             at /home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:65:22
   6: arrow2::io::parquet::read::deserialize::columns_to_iter_recursive::{{closure}}
             at /home/ritchie46/code/arrow2/src/io/parquet/read/deserialize/mod.rs:301:29
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/ops/function.rs:301:13
   8: core::option::Option<T>::map
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/option.rs:929:29
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/map.rs:103:9
  10: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1885:9
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/map.rs:103:9
  12: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1885:9
  13: polars_io::parquet::read_impl::array_iter_to_series
             at /home/ritchie46/code/polars/polars/polars-io/src/parquet/read_impl.rs:32:24
  14: polars_io::parquet::read_impl::read_parquet::{{closure}}::{{closure}}
             at /home/ritchie46/code/polars/polars/polars-io/src/parquet/read_impl.rs:126:29
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/ops/function.rs:268:13
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/ops/function.rs:301:13
  17: core::option::Option<T>::map
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/option.rs:929:29
  18: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/map.rs:103:9
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/map.rs:103:9
  20: <core::iter::adapters::take_while::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/take_while.rs:46:21
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/iter/adapters/map.rs:103:9
  22: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/vec/mod.rs:2716:35
  23: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/vec/spec_extend.rs:18:9
  24: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/vec/mod.rs:2690:9
  25: <rayon::iter::extend::ListVecFolder<T> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/extend.rs:73:9
  26: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/while_some.rs:139:21
  27: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/ritchie46/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1
```

**Comment by jorgecarleitao** [comment]
I tried to simplify the example further and I am unable to reproduce it in arrow2 alone.

```python
import io

import polars as pl  # 0.13.51

import numpy as np


df1 = pl.DataFrame(
    {
        "a": [1]*2,
        "l": [[1] for j in range(0, 2)],
    }
)
df2 = pl.DataFrame(
    {
        "a": [2]*3,
        "l": [[2] for j in range(0, 3)],
    }
)
#df1 = pl.DataFrame({'a': np.random.randint(0, high=10, size=20), 'l': [[i for i in range(0, 5 + j%2)] for j in range(0, 20)]})
#df2 = pl.DataFrame({'a': np.random.randint(0, high=10, size=50), 'l': [[i for i in range(0, 3 + j%3)] for j in range(0, 50)]})

df = df1.vstack(df2)

print(df)


for use_pyarrow in [False, True]:
    f = io.BytesIO()
    df.to_parquet(f)
    df.to_parquet("bla.parquet")
    f.seek(0)

    read = pl.read_parquet(f, use_pyarrow=use_pyarrow)
    print(read)

    assert read.frame_equal(df)
```

this gives `The columns lengths in the DataFrame are not equal.` (in line `print(read)` but running

```bash
cargo run --example parquet_read --features io_parquet,io_parquet_compression  -- bla.parquet
```

happily consumes it (and when I print each chunk, I get)

```
Chunk { arrays: [Int64[1, 1], LargeListArray[[1], [1]]] }
Chunk { arrays: [Int64[2, 2, 2], LargeListArray[[2], [2], [2]]] }
```

likewise, if I use the original example, I get some chunks:

```
Chunk { arrays: [Int64[7, 9, 7, 8, 8, 0, 9, 7, 8, 9, 4, 5, 7, 8, 8, 8, 0, 0, 3, 0], LargeListArray[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5]]] }
Chunk { arrays: [Int64[7, 6, 0, 3, 9, 8, 9, 1, 2, 9, 8, 5, 5, 7, 7, 2, 9, 3, 5, 7, 4, 8, 2, 1, 8, 3, 3, 0, 8, 4, 4, 9, 7, 8, 4, 5, 4, 1, 7, 4, 2, 6, 6, 5, 8, 3, 2, 2, 8, 0], LargeListArray[[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4], [0, 1, 2], [0, 1, 2, 3]]] }
```

does polar do something between reading the chunks and organizing them in a DataFrame? From the first experiment it seems that there is some slicing going on?

**Comment by ritchie46** [comment]
Hmm.. I shall investigate more on the polars side.
