### ISSUE TITLE
Loading data from S3 without running into "too many open files" error

### ISSUE THREAD

**Issue by mdrach** [jorgecarleitao/arrow2#953]
We've recently attempted to upgrade to arrow v0.10.0 but are having issues adapting our S3 shard download code to use the new API.  We're using `read_columns_many_async` which accepts a Reader-producing `factory`, and we've found that a new Reader is created per column per row group per shard.  For large files (100s of shards, 10s of columns, 10s of row groups per shard) , file loading can open 10,000+ concurrent connections to S3, causing this error:

```
...
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/time/driver/entry.rs:549:13
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/time/driver/entry.rs:549:13
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/time/driver/entry.rs:549:13
Error: internal

Caused by:
    Io error: unavailable: error sending request for url (<redacted>): error trying to connect: dns error: Too many open files (os error 24)
```

When using the old API, using `get_page_stream` allow us to re-use a single Reader per shard.  Our reader would stream in 1MB+ sized chunks of a given page at a time, caching the contents of the most-recent fetch so we could lazily fetch additional pieces of the file.

How might we limit the number of concurrent connections to S3 using this new API? 
    a. Should we cache the results of our 1MB+ requests to S3 at layer other than the Reader level to reduce redundant fetches?
    b. Related: Is there an alternative way to "re-use" Readers across column/row group/shard fetches?
   
Thanks for helping us determine how to use the new `arrow2` parquet reader API for our use case.

**Comment by jorgecarleitao** [comment]
wonderful questions 🤩

So, the reason for the current design is based on two ideas:

* in nested fields, we need to deserialize multiple columns at once. In these cases, we need to be able to hold multiple clones of the reader (thus the factory), for reading the columns concurrently.
* the work being done in arrow2 is intrinsically CPU-bounded, which is not suitable to be done inside an `async` context due to the cooperative scheduling nature of Rust's `async`.

My understanding is that you are currently `join_all` over all row groups and shards, which will cause everything to download concurrently, hitting some network limit (usually number of open sockets in unix).

I.e. we need some mechanism to limit concurrently. One option I know of is to use a stream of futures (e.g. each `(row group, shard)` is an item from the stream, each future yields a deserialized row group) and limit the number of futures that can run concurrently at any given time, via [`buffer_unordered`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.buffer_unordered). Could this work?

**Comment by mdrach** [comment]
That solution would be okay for our use case, but would result in some wasted downloads..

Here are some numbers to add some color to our problem:

We are trying to load a 17.9GB dataset in from S3:
num shards = 249, num row groups per shard = 7, num columns (per row group) = 17
avg shard size ~ 70 MB, avg row group size ~ 10MB, avg column size is ~600KB.

Our Reader downloads from S3 in 1-8MB chunks to maximize throughput.

The proposal, creating a new Reader per row group, would create 249 * 7 = 1743 Readers here.  We can limit concurrent shard downloads, and limiting concurrent row group downloads within each shard, as you mentioned, could be helpful as well.

It's not a perfect solution: a Reader per row group prevents using all of the data that we download into our Reader's buffer.  For example: if we assume that row groups are >= 8MB, then if a given Reader downloads in 8MB chunks, we're throwing out (worst case) 50% of the data that we download in a given reader (e.g. when all row groups are 8.1MB).

Our current solution, uses the older arrow2 api which allows a single reader _per shard_, so we use nearly all the data that we download.  See below.
```
        let pages: Vec<Result<CompressedDataPage, ParquetError>> =
            get_page_stream(column, &mut reader, None, page_buffer)
                .await
                .map_err(Error::internal)?
                .collect()
                .await;
```
